stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - params.data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - src/data_preprocessing.py
    outs:
    - data/processed
  feature_eng:
    cmd: python src/feature_eng.py
    deps:
    - src/feature_eng.py
    params:
    -feature_eng.max_features
    outs:
    - data/features
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/features
    - src/model_building.py
    params:
    -model_building.n_estimators
    -model_building.learning_rate
    outs:
    - model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - model.pkl
    - src/model_evaluation.py
    metrics:
    - metrics.json
